### ISSUE TITLE
Python Setuptools not recognized

### ISSUE THREAD

**Issue by pittzgal** [Battelle/afl-unicorn#17]
Hi,

After I run "sudo ./build_unicorn_support.sh" under unicorn_mode directory, I got this error:

[*] Performing basic sanity checks...
[-] Error: Python setup-tools not found. Run 'sudo apt-get install python-setuptools'.

I get this error even after I installed the setuptools and rerun the script. I use an Ubuntu 18.04. Has anyone encountered similar problems?

**Comment by colorlight** [comment]
same problem!

**Comment by colorlight** [comment]
I comment the check condition, now I can compile the project, but  the parmeter -U is useless.
I think it may be because the python upgrading staff.

**Comment by njv299** [comment]
This error message is coming from this check failing:
```if ! which easy_install > /dev/null; then

  echo "[-] Error: Python setup-tools not found. Run 'sudo apt-get install python-setuptools'."
  exit 1

fi```

Basically, for some reason the command `easy_install` is not available in the context in which you are running the `build_unicorn_support.sh` script. Normally you can install that via the `sudo apt-get install python-setuptools` command. I'm not sure why that command isn't found in your case, but I'm guessing that the answer is contained somewhere in this discussion: https://askubuntu.com/questions/1040392/easy-install-command-not-found

Let me know if that solves it. Thanks!

**Comment by colorlight** [comment]
Thanks Nathan, I solve it according to the link you mentioned. https://askubuntu.com/questions/1040392/easy-install-command-not-found.

Use this command
`python /usr/lib/python2.7/dist-packages/easy_install.py pip`

And add the `easy_instal`l cmd to the sudoers, otherwise the build script can't find the easy_install under the sudo privilege yet.

However, when I compile with no modification of the build script, the afl-fuzz still cannot identify the -U parmeter!

**Comment by bstee615** [comment]
At first, I ran into the same error, because easy_install is deprecated on modern versions of setuptools. I submitted the PR to use a more modern check for setuptools.
